### ISSUE TITLE
Ores still generated despite generateOres: false

### ISSUE THREAD

**Issue by leagris** [TechReborn/TechReborn#983]
### Version:
* TechReborn-1.11.2-2.1.6.76-universal.jar
* Full mod list [here](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/master/BR-1.11.2/modlist.md)

### Specific settings:
[config/techreborn/ores.hjson](https://github.com/Beyond-Reality/BeyondRealityModPack/blob/977c832a3e41427ab4e6bb33e7e19b6c22796912/BR-1.11.2/config/techreborn/ores.hjson)
### Description
Ore generation is not disabled by setting  `generateOres` to `false` in `ores.hjson`:
```YAML
{
  generateTechRebornFeatures: true
  generateOres: false
  retroGenOres: false
}
```
